version: '2'
services:
    micoserviceduapplication-app:
        image: micoserviceduapplication
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://micoserviceduapplication-mysql:3306/micoserviceduapplication?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    micoserviceduapplication-mysql:
        extends:
            file: mysql.yml
            service: micoserviceduapplication-mysql
